rpcserver: add ticketsforaddress tests.
decred/dcrd pull request #2405
Opened 2020-10-07 12:28 UTC by dnldd

This adds rpc tests for `ticketsforaddress`.

Work towards #2069.

2020-10-07 12:41 UTC, dnldd commented
```sh
go tool cover -func=cov.out | grep -E handleTicketsForAddress
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:4962:      handleTicketsForAddress          100.0%
```

2020-10-13 11:28 UTC, rstaudt2 requested changes
Test coverage looks good!  Had a couple of minor inline comments.

2020-10-14 09:58 UTC, rstaudt2 approved these changes

2020-10-24 07:59 UTC, davecgh reviewed
Looks good.  Needs to squash the review commit and also rebase to resolve the merge conflict and then I'll approve and merge it.

2020-10-26 16:55 UTC, davecgh approved these changes

2020-10-26 16:55 UTC, merged