rpcserver: add ticketvwap tests.
decred/dcrd pull request #2406
Opened 2020-10-07 14:41 UTC by dnldd

This adds rpc tests for `ticketvwap`.

Work towards #2069.

2020-10-07 14:45 UTC, dnldd commented
```sh
go tool cover -func=cov.out | grep -E handleTicketVWAP
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:4996:              handleTicketVWAP                100.0%
```

2020-10-14 10:12 UTC, rstaudt2 requested changes
Test coverage looks good, just had a couple of very minor stylistic comments.

2020-10-14 10:12 UTC, rstaudt2 commented on internal/rpcserver/rpcserverhandlers_test.go
> +				fmt.Errorf("unable to fetch header by height")
Same nit as in the other PR to use `errors.new`

2020-10-14 10:12 UTC, rstaudt2 commented on internal/rpcserver/rpcserverhandlers_test.go
> +		name:    "handleTicketVWAP: ok,",
Looks like a leftover comma left here
```suggestion
		name:    "handleTicketVWAP: ok",
```

2020-10-14 10:12 UTC, rstaudt2 commented on internal/rpcserver/rpcserverhandlers_test.go
> +		name:    "handleTicketVWAP: ok, no parameters.",
For consistency with all other tests, I'd remove the trailing period at the end here and below

2020-10-24 08:14 UTC, davecgh reviewed
I agree with all of @rstaudt2's review comments.  Otherwise, looks good.

2020-10-26 11:11 UTC, rstaudt2 approved these changes

2020-10-26 16:55 UTC, davecgh approved these changes

2020-10-26 16:56 UTC, davecgh commented
Approved, but needs a rebase to resolve the merge conflict before I can merge.

2020-10-26 22:15 UTC, davecgh approved these changes

2020-10-26 22:15 UTC, merged