rpcserver: add handleTxFeeInfo tests.
decred/dcrd pull request #2407
Opened 2020-10-07 21:39 UTC by dnldd

This adds rpc tests for `handleTxFeeInfo`.

Work towards #2069.

2020-10-07 21:41 UTC, dnldd commented
```sh
go tool cover -func=cov.out | grep -E handleTxFeeInfo
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:5054:              handleTxFeeInfo                 100.0%
```

2020-10-15 10:07 UTC, rstaudt2 requested changes

2020-10-15 10:07 UTC, rstaudt2 commented on internal/rpcserver/rpcserverhandlers_test.go
> +				fmt.Errorf("unable to fetch block by height")
Same nit as in the other PR to use `errors.new` here instead for consistency with the other tests, and since no formatting is required.

2020-10-16 10:04 UTC, rstaudt2 commented on internal/rpcserver/rpcserverhandlers_test.go
> +	heightRangeFn                   func(startHeight, endHeight int64) ([]chainhash.Hash, error)
This comment can be marked resolved - saw that this was not needed for this PR, but was needed in https://github.com/decred/dcrd/pull/2408 that you have on top of this to handle mocking when the function is called multiple times within a test

2020-10-26 17:26 UTC, davecgh approved these changes

2020-10-26 17:27 UTC, davecgh commented
Needs rebase, but probably should wait until #2406 is rebased and merged since it'll need another one after that.

2020-10-26 22:28 UTC, merged