blockchain: fix errorlint warnings
decred/dcrd pull request #2411
Opened 2020-10-12 17:35 UTC by dajohi

2020-10-12 22:36 UTC, dnldd approved these changes

2020-10-16 00:51 UTC, davecgh requested changes

2020-10-16 00:51 UTC, davecgh commented on blockchain/validate.go
> +		switch {
It seems odd to unwrap this and then use `errors.Is` which it already handles that.  Probably should be:

```Go
// Convert standalone package rule errors to blockchain rule errors.
switch{
case errors.Is(err, standalone.ErrUnexpectedDifficulty):
	return ruleError(ErrUnexpectedDifficulty, err.Error())
...
}

return err
```

2020-10-17 00:20 UTC, davecgh approved these changes

2020-10-17 00:20 UTC, merged