rpcserver: add handleGetVoteInfo tests.
decred/dcrd pull request #2432
Opened 2020-10-16 13:35 UTC by dnldd

This adds rpc tests for `handleGetVoteInfo`.

Work towards #2069.

2020-10-16 13:36 UTC, dnldd commented
```sh
go tool cover -func=cov.out | grep -E "handleGetVoteInfo"
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:3347:    handleGetVoteInfo                100.0%
```

2020-10-29 10:08 UTC, rstaudt2 reviewed
Looks good, just one minor comment on the test indentation.

2020-10-29 10:08 UTC, rstaudt2 commented on internal/rpcserver/rpcserverhandlers_test.go
> +		{
Formatting is off here - this can be moved to the line above and then have the below shifted left like in the other tests

2020-10-29 11:26 UTC, rstaudt2 approved these changes

2020-11-04 05:48 UTC, davecgh requested changes
Looks great overall.  Just some formatting nits.

2020-11-04 05:48 UTC, davecgh commented on internal/rpcserver/rpcserverhandlers_test.go
> +		Choices: []types.Choice{
Please use the newer, more compact style of:

```Go
Choices: []types.Choice{{
	ID:          "abstain",
	Description: "abstain voting for change",
	Bits:        0,
	IsAbstain:   true,
	IsNo:        false,
	Count:       20,
	Progress:    0.2,
}, {
	....
}}

2020-11-04 05:48 UTC, davecgh commented on internal/rpcserver/rpcserverhandlers_test.go
> +		Choices: []types.Choice{
Same here.

2020-11-04 21:23 UTC, davecgh approved these changes
Needs rebase to resolve merge conflict.  Good to go otherwise.

2020-11-04 21:35 UTC, merged