mining: Move block chain functions to Config.
decred/dcrd pull request #2436
Opened 2020-10-21 02:03 UTC by rstaudt2

This updates mining to take in the block chain related functions that it requires rather than requiring a blockchain.BlockChain instance.

This allows for alternate implementations to be provided for these functions, such as for testing.

Some of the functions, such as `BlockByHash(hash *chainhash.Hash)`, are only used for the tip and therefore _could_ have been defined as something like `BestBlock()` instead (which would internally call `BestSnapshot` and pass that hash to `BlockByHash`).  I decided against this since mining already has already fetched `blockchain.BestState` in most cases, so it would be a bit less efficient to be calling `BestSnapshot` again within these functions.

2020-10-21 02:13 UTC, davecgh commented
> Some of the functions, such as `BlockByHash(hash *chainhash.Hash)`, are only used for the tip and therefore _could_ have been defined as something like `BestBlock()` instead (which would internally call `BestSnapshot` and pass that hash to `BlockByHash`). I decided against this since mining already has already fetched `blockchain.BestState` in most cases, so it would be a bit less efficient to be calling `BestSnapshot` again within these functions.

Regarding this point, one of the things I really want to work towards changing in the future is ensuring that all of the funcs end up taking in a block hash as opposed to assuming the current tip.  While it works with a high degree of accuracy due to the fact blocks are extremely infrequent relative to the execution time, the current logic is realistically racy in general due to the fact that the tip might have changed in between the point you call two funcs which rely on implicitly working with it since they independently lock and unlock.

I should also note that in all contexts which this occurs, it doesn't really have super negative consequences because it either produces a template the fails which will cause another one to be built which won't since the new attempt is super unlikely to also have the tip change in between due to target block times.  Other cases are similar, but it can very infrequently result in needless retries and even potentially slightly incorrect and/or outdated data delivered over RPC.

2020-10-21 02:24 UTC, rstaudt2 commented
> If all of the funcs end up taking the block hash, there would be a single call to determine the current tip hash and then that hash would be used in all of the calls which would prevent the aforementioned possibilities altogether.

👍 Makes sense, sounds like a good approach to me.

2020-10-22 11:18 UTC, dnldd commented on internal/mining/mining.go
> +	// requirement.  The block must connect to the current tip of the main chain or
`The block must connect to the current tip of the main chain or its parent`, this is already stated in the sentence prior.

2020-10-22 11:20 UTC, dnldd commented on internal/mining/mining.go
> +	BlockManager blockManagerFacade
Considering the detail provided for the other config fields these could be more descriptive.

2020-10-22 23:24 UTC, davecgh requested changes
Looks great overall and it's a good set of changes.

2020-10-22 23:24 UTC, davecgh commented on internal/mining/mining.go
> +	// TimeSource defines a time source to use.
These comments should be made a bit more explicit like the others as opposed to stating the obvious.  They don't seem to be especially useful as they are.

2020-10-23 03:03 UTC, rstaudt2 commented
Thanks for the reviews.  I adjusted the comments on items that were called out to be more verbose.

2020-10-23 03:10 UTC, davecgh approved these changes
Thanks for the updates.  Looks good!

2020-10-23 10:49 UTC, dnldd approved these changes

2020-10-23 10:54 UTC, merged