secp256k1/ecdsa: Consistent sig recovery errors.
decred/dcrd pull request #2914
Opened 2022-04-03 23:41 UTC by davecgh

This converts the error handling in compact signature recovery to be consistent with the rest of the code base such that it returns concrete errors that support errors.Is/As and thus are programmatically detectable by callers.

2022-04-05 21:59 UTC, dnldd requested changes
Looks good besides minor typo.

2022-04-05 21:59 UTC, dnldd commented on dcrec/secp256k1/ecdsa/error.go
> +	// key from a compact signature results in a point that is not on the
s / public key key / public key

2022-04-05 22:33 UTC, davecgh commented on dcrec/secp256k1/ecdsa/error.go
> +	// key from a compact signature results in a point that is not on the
Nice catch.  Fixed.

2022-04-05 23:03 UTC, dnldd approved these changes

2022-04-06 01:35 UTC, dajohi approved these changes

2022-04-07 02:18 UTC, JoeGruffins approved these changes

2022-04-07 15:17 UTC, rstaudt2 approved these changes

2022-04-07 16:06 UTC, merged