blockchain: Remove unused params.
decred/dcrd pull request #2918
Opened 2022-04-07 18:30 UTC by dajohi

2022-04-07 20:46 UTC, davecgh requested changes
Looks good overall.

2022-04-07 23:44 UTC, dajohi commented on blockchain/treasury_test.go
> +	return tsr, err
adjusted

2022-04-07 23:44 UTC, dajohi commented on blockchain/chainio.go
> +func putTxToMinimalOutputs(target []byte, tx *dcrutil.Tx) {
reverted

2022-04-07 23:46 UTC, davecgh approved these changes

2022-04-08 10:47 UTC, dnldd approved these changes

2022-04-11 22:22 UTC, merged