[release-v1.7] indexers: fix subscribers race.
decred/dcrd pull request #2921
Opened 2022-04-10 14:29 UTC by dnldd

This fixes a race accessing an indexer's subscribers waiting on index updates.

fixes  #2913

2022-04-12 12:01 UTC, dnldd commented on blockchain/indexers/common.go
> +		case _, open = <-subscription:
good catch, thanks. Will rework it soon.

2022-04-26 03:55 UTC, davecgh approved these changes
EDIT: This still has races and panics.

2022-04-26 05:41 UTC, davecgh requested changes
Actually after doing a bit more testing, I see this still isn't fixed and can panic now:

```
panic: close of closed channel

goroutine 71 [running]:
github.com/decred/dcrd/blockchain/v4/indexers.maybeNotifySubscribers({0x18557d0, 0xc000072400}, {0x1857b88, 0xc000075f80})
        src/github.com/decred/dcrd/blockchain/indexers/common.go:727 +0x27e
github.com/decred/dcrd/blockchain/v4/indexers.updateIndex({0x18557d0, 0xc000072400}, {0x1857b88?, 0xc000075f80?}, 0xc037748380)
        src/github.com/decred/dcrd/blockchain/indexers/common.go:813 +0x1a7
github.com/decred/dcrd/blockchain/v4/indexers.(*IndexSubscriber).Run(0xc0001d20c0, {0x18557d0, 0xc000072400})
        src/github.com/decred/dcrd/blockchain/indexers/indexsubscriber.go:360 +0x3f6
main.(*server).Run.func7({0x18557d0?, 0xc000072400?}, 0xc000278780)
        src/github.com/decred/dcrd/server.go:3149 +0x3e
created by main.(*server).Run
        src/github.com/decred/dcrd/server.go:3148 +0x5a5
```

2022-04-26 11:47 UTC, dnldd commented
Noticed the issue, `maybeNotifySubscribers` and `purgeIndexerSubscription` are closing the subscriber channel without knowing the state it's in prior. Will need to synchronize the channel closes. Can't see a way around reading the channel to check its state yet, should be fine since the waitForSync receiver is expecting a closed channel when there is an index  update. Looking for a better way however.

2022-04-27 07:39 UTC, davecgh approved these changes
I've performed full syncs on both mainnet and testnet with the race detector enabled and while constantly spamming requests for both `existsaddress` and `getrawtransaction` without issue.

2022-04-28 08:00 UTC, JoeGruffins approved these changes

2022-05-04 05:18 UTC, merged