docker: Update image to golang:1.22.4-alpine3.20.
decred/dcrd pull request #3370
Opened 2024-06-13 04:45 UTC by davecgh

This updates the docker image to golang:1.22.4-alpine3.20.

To confirm the new digest:

```
$ docker pull golang:1.22.4-alpine3.20
1.22.4-alpine3.20: Pulling from library/golang
...
Digest: sha256:9bdd5692d39acc3f8d0ea6f81327f87ac6b473dd29a2b6006df362bff48dd1f8
...
```

2024-06-14 23:55 UTC, ukane-philemon requested changes
Looks like em digest has changed

```
% docker pull golang:1.22.4-alpine3.20
1.22.4-alpine3.20: Pulling from library/golang
......
Digest: sha256:6522f0ca555a7b14c46a2c9f50b86604a234cdc72452bf6a268cae6461d9000b
Status: Downloaded newer image for golang:1.22.4-alpine3.20
....

```

2024-06-15 00:14 UTC, davecgh commented
> Looks like em digest has changed
> 
> ```
> % docker pull golang:1.22.4-alpine3.20
> 1.22.4-alpine3.20: Pulling from library/golang
> ......
> Digest: sha256:6522f0ca555a7b14c46a2c9f50b86604a234cdc72452bf6a268cae6461d9000b
> Status: Downloaded newer image for golang:1.22.4-alpine3.20
> ....
> ```

Yep, looks like it has:
```
$ docker pull golang:1.22.4-alpine3.20
1.22.4-alpine3.20: Pulling from library/golang
d25f557d7f31: Already exists
8b732c871fea: Pull complete
060aaf7efd06: Pull complete
7d1964877d68: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:6522f0ca555a7b14c46a2c9f50b86604a234cdc72452bf6a268cae6461d9000b
Status: Downloaded newer image for golang:1.22.4-alpine3.20
```
Confirmed.

Updated PR.

2024-06-15 01:05 UTC, ukane-philemon approved these changes

2024-06-15 01:49 UTC, matthawkins90 commented
Also confirmed:
`Digest: sha256:6522f0ca555a7b14c46a2c9f50b86604a234cdc72452bf6a268cae6461d9000b`

2024-06-15 01:49 UTC, matthawkins90 approved these changes

2024-06-15 03:20 UTC, merged