mixing/mixclient: Add missing copyright headers.
decred/dcrd pull request #3399
Opened 2024-06-27 10:56 UTC by jholdstock

2024-06-27 13:18 UTC, jrick requested changes
Some files taken from the old cspp repo should have longer/older date ranges.

2024-06-27 13:18 UTC, jrick commented on mixing/field.go
> +// Copyright (c) 2024 The Decred developers
This is https://github.com/decred/cspp/blob/master/dcnet/field.go

`// Copyright (c) 2019-2024 The Decred developers`

2024-06-27 13:18 UTC, jrick commented on mixing/mixclient/limits.go
> +// Copyright (c) 2024 The Decred developers
Adapted from https://github.com/decred/cspp/blob/master/coinjoin/size.go.

`// Copyright (c) 2023-2024 The Decred developers`

2024-06-27 14:09 UTC, jrick approved these changes

2024-06-27 18:47 UTC, matthawkins90 approved these changes

2024-06-28 20:06 UTC, davecgh approved these changes

2024-06-28 20:06 UTC, merged